### PR TITLE
DAC6-916:add scala formatting plugin scalafmt

### PR DESCRIPTION
**Pull request by ashwinirudrappa**

### CODE REVIEW

**Comment by ashwinirudrappa** [comment]
test this please

**Comment by ashwinirudrappa** [comment]
test this please

**Comment by ashwinirudrappa** [comment]
test this please

**Comment by ashwinirudrappa** [comment]
test this please

**Comment by ashwinirudrappa** [comment]
test this please

**Review by iservport — APPROVED** [review]
LGTM

**Pull request merged**
